###
# listar delivery
GET http://localhost:3008/deliverys

### 
# listar delivery com clientes
GET http://localhost:3008/deliverys?_embed=cliente

### 
# Pegar delivery 1
GET http://localhost:3008/deliverys/5cc3

###

# Pegar delivery 1
GET http://localhost:3008/deliverys/5cc3?_embed=cliente

###
# Criar delivery
POST http://localhost:3008/deliverys
content-type: application/json

{
  "id": "",
      "tipo": "BLAZER",
      "subTipo": "BLAZER COM DETALHE",
      "preco": 45.00,
      "imagemUrl": "/assets/img/blazer.png"
}
###
# alterar dados do delivery
PUT http://localhost:3008/deliverys/5cc3
content-type: application/json

{
  "deliveryTipo": "Retirada",
  "deliveryData": "2024/09/28"
}

###
# busca delivery

GET http://localhost:3008/deliverys?nome=João&telefone_like=12340000
#GET http://localhost:3008/deliverys?nome_like=Maria&telefone_like=99999999_sort=nome&_order=asc


###
